sudo: required

language: generic

services:
- docker

before_install:
- docker pull debian:stretch
- mkdir /tmp/docker
- cp ./Makefile /tmp/docker
- cp ./m4lvin-packaging-B2CF44CE.asc.gpg /tmp/docker
- cp -vr ./upload /tmp/docker/upload

install:
- docker run --rm --interactive --tty --env PGPPHRASE --env PGPWRAPPER -v /tmp/docker/:/build -w /build debian:stretch /bin/bash -c "apt-get update && apt-get install -y -qq make --no-install-recommends && make"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
  local_dir: /tmp/docker/upload/

env:
  global:
  - secure: "XFeB8bVrv7Vo0hywsQn20JQQ48b6kzsDXF/dyJ7BpxGDjQocJwz9P8RkXTWHXduxx8lWQZTY3UNC9OoQOPm5WmzXCtQqGpWnixJC0BwP9YAHP8154TY9izcUi90SyJtPnjAQN2WUlZBD1hgc4aNx+6fDqq8+egI3DxaO66PZ2JrRvR9k/w/QbE8t4sdRMPF7wOgg96vv5D2WsVtJzBXOhc06LaJPyMjUm0s0W7NWUhHcuttsOAuoPCHLG2l7zQSdVlSpeBgQVSYMnhCOMLIy1fY1tY0/1Fd1sJzt9jQlygEmShTkAt3YwuF/IQ4CSGSAn7E4vGXb1ZJljbaWgK+sA859e5zeAlX29HCPSt4peu/O/QsksiW00y7XtA8fUpshzBDXTzJiDxoWbb9ZN+Ky+VEfqDhiVdhgZG+YzubzhHVqhS1njk/Q4qPAPUN1RlCmm/NoIk/jytudtzjMvHfJ4y9etaXf+2dhjthg5TFBsuECtDbBzBcw66PRHHifhp8e1x5dshsXujp3UYafsRLdwMmLm08/jUECvQCPVI1xGXZleJrUphwi72kCYu03phTFouoNM5XUWE6Li8yuVDs3K6k63kBwVFWe6b0OJr0N02KKVT/E3jdwsiCOfzubXsf+nIkXE6D5I7ItHrI4djdRGjUYWFl0vyMNRm+W8j9/4wU="
  - secure: "Q1q9FU0dxwqb5MN1cS/9vx7y05fkpYxiuvWiL7l1NVJmLQahZX2t5VYPHfxbPHce06qiVU5UgkQr7jlV+tLtQ7rC4ClOt3b3Mbjqz1UF45FbVuqiTHIfZCMnQp14aAdfqxvOmD9SY9LpwXDzJgqH/YO4s3qmPxKVAvMqRFUWhDEhRHDGwvyBcOlKXwCtFZ+q1jkpg6Z9o1PCX5xTq3K63KO/PIcndls7CK8cTwR10x6me8yN29abfgpdhhLzPSy28ZA2/avuNd2tCH9jCEuVHcZolIztxIGp+V+9P3/VN7X8Y2+YN3jY3btxDWuKEVQ1NkGO59ntQVAgcVm326SxbnlRgnMLBzpCxoOatyetTQ9Twe5Ro4+c0ZZoP4p08zP5xclWum0UeGIWbT9Ry71mdV+DbyNKKepp1uxh7obaAmsImb38ZmnD9PHbLsMIf3SE2QxzyZjwTbAhu/4NhPvdqS2nNHI39D07C9WyqNhmbyKAQw26a7i4TnB6pXXQdieaK7s4QqVPOOGkNjyqtI27BnAUCdJJ54JXfIazTVfnAo9YRTvriDEONDrZ6Uz/7+gw2ZUvwXNoOlQMRfwasPmOlx/8oPDnzK3HYth+z3vSefBHO60vHm4AquBqd+ZvoKTLrJhBOlvQJzgaeA7dPJtRjaevpccNihAz746NJ4zjDhQ="
